### ISSUE TITLE
Could not load plugin on 1.15.2

### ISSUE THREAD

**Issue by Bloodlex** [Xenoyia/XenTradingCards#1]
Please help cannot load plugin on 1.15.2 😢 

This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version **1.15.2-R0.1-SNAPSHOT**)

**Xen's Trading Cards**: **5.0.3**

[16:50:45 ERROR]: Could not load 'plugins\TradingCards-5.0.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-384]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by Xenoyia** [comment]
It's built for the current version right now (1.16). I will see if I can make it compatible with 1.15.

**Comment by Xenoyia** [comment]
> 
> 
> Please help cannot load plugin on 1.15.2 😢
> 
> This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version **1.15.2-R0.1-SNAPSHOT**)
> 
> **Xen's Trading Cards**: **5.0.3**
> 
> [16:50:45 ERROR]: Could not load 'plugins\TradingCards-5.0.3.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
> at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-384]
> at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-384]
> at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-384]
> at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-384]
> at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-384]
> at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-384]
> at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-384]
> at java.lang.Thread.run(Thread.java:832) [?:?]

Backwards compatibility including 1.14 and 1.15 has been added with the latest update (5.0.4).
